vich_uploader:
    db_driver: orm
    metadata:
        type: 'annotation'
    mappings:
        image_local:
            uri_prefix: /uploads/local
            upload_destination: '%kernel.project_dir%/public/uploads/local'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
  